# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         X11-FreeDesktop-DesktopEntry
version:      0.01
version_from: lib/X11/FreeDesktop/DesktopEntry.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
